from com.android.monkeyrunner import MonkeyRunner, MonkeyDevice
device = MonkeyRunner.waitForConnection()

device.touch(50, 296, "DOWN_AND_UP")
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_9','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_1','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_9','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_7','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_5','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_7','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_7','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_9','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_5','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_3','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_BACK','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.touch(214, 730, "DOWN_AND_UP")
MonkeyRunner.sleep(40)
device.touch(241, 689, "DOWN_AND_UP")

device.press('KEYCODE_BACK','DOWN_AND_UP')
MonkeyRunner.sleep(10)




device.touch(50, 296, "DOWN_AND_UP")
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_9','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_1','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_9','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_5','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_6','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_1','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_6','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_1','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_1','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_7','DOWN_AND_UP')
MonkeyRunner.sleep(0.5)
device.press('KEYCODE_BACK','DOWN_AND_UP')
MonkeyRunner.sleep(2)
device.touch(214, 730, "DOWN_AND_UP")
MonkeyRunner.sleep(40)
device.touch(241, 689, "DOWN_AND_UP")
device.press('KEYCODE_BACK','DOWN_AND_UP')

